//
//  Datos.swift
//  Hamburguesas en el mundo
//
//  Created by Luis Antonio Jimenez Velasco on 24/04/16.
//  Copyright © 2016 Luis Antonio Jimenez Velasco. All rights reserved.
//

import Foundation
import UIKit

class ColeccionDePaises {
    
    var paises: [String] = ["Afganistán",
                            "Albania",
                            "Alemania",
                            "Andorra",
                            "Angola",
                            "Antigua y Barbuda",
                            "Arabia Saudita",
                            "Argelia",
                            "Argentina",
                            "Armenia",
                            "Australia",
                            "Austria",
                            "Azerbaiyán",
                            "Bahamas",
                            "Bangladés",
                            "Barbados",
                            "Baréin",
                            "Bélgica",
                            "Belice",
                            "Benín",
                            "Bielorrusia",
                            "Birmania",
                            "Bolivia",
                            "Bosnia y Herzegovina",
                            "Botsuana",
                            "Brasil",
                            "Brunéi",
                            "Bulgaria",
                            "Burkina Faso",
                            "Burundi",
                            "Bután",
                            "Cabo Verde",
                            "Camboya",
                            "Camerún",
                            "Canadá",
                            "Catar",
                            "Chad",
                            "Chile",
                            "China",
                            "Chipre",
                            "Ciudad del Vaticano",
                            "Colombia",
                            "Comoras",
                            "Corea del Norte",
                            "Corea del Sur",
                            "Costa de Marfil",
                            "Costa Rica",
                            "Croacia",
                            "Cuba",
                            "Dinamarca",
                            "Dominica",
                            "Ecuador",
                            "Egipto",
                            "El Salvador",
                            "Emiratos Árabes Unidos",
                            "Eritrea",
                            "Eslovaquia",
                            "Eslovenia",
                            "España",
                            "Estados Unidos",
                            "Estonia",
                            "Etiopía",
                            "Filipinas",
                            "Finlandia",
                            "Fiyi",
                            "Francia",
                            "Gabón",
                            "Gambia",
                            "Georgia",
                            "Ghana",
                            "Granada",
                            "Grecia",
                            "Guatemala",
                            "Guyana",
                            "Guinea",
                            "Guinea ecuatorial",
                            "Guinea-Bisáu",
                            "Haití",
                            "Honduras",
                            "Hungría",
                            "India",
                            "Indonesia",
                            "Irak",
                            "Irán",
                            "Irlanda",
                            "Islandia",
                            "Islas Marshall",
                            "Islas Salomón",
                            "Israel",
                            "Italia",
                            "Jamaica",
                            "Japón",
                            "Jordania",
                            "Kazajistán",
                            "Kenia",
                            "Kirguistán",
                            "Kiribati",
                            "Kuwait",
                            "Laos",
                            "Lesoto",
                            "Letonia",
                            "Líbano",
                            "Liberia",
                            "Libia",
                            "Liechtenstein",
                            "Lituania",
                            "Luxemburgo",
                            "Madagascar",
                            "Malasia",
                            "Malaui",
                            "Maldivas",
                            "Malí",
                            "Malta",
                            "Marruecos",
                            "Mauricio",
                            "Mauritania",
                            "México",
                            "Micronesia",
                            "Moldavia",
                            "Mónaco",
                            "Mongolia",
                            "Montenegro",
                            "Mozambique",
                            "Namibia",
                            "Nauru",
                            "Nepal",
                            "Nicaragua",
                            "Níger",
                            "Nigeria",
                            "Noruega",
                            "Nueva Zelanda",
                            "Omán",
                            "Países Bajos",
                            "Pakistán",
                            "Palaos",
                            "Panamá",
                            "Papúa Nueva Guinea",
                            "Paraguay",
                            "Perú",
                            "Polonia",
                            "Portugal",
                            "Reino Unido",
                            "República Centroafricana",
                            "República Checa",
                            "República de Macedonia",
                            "República del Congo",
                            "República Democrática del Congo",
                            "República Dominicana",
                            "República Sudafricana",
                            "Ruanda",
                            "Rumanía",
                            "Rusia",
                            "Samoa",
                            "San Cristóbal y Nieves",
                            "San Marino",
                            "San Vicente y las Granadinas",
                            "Santa Lucía",
                            "Santo Tomé y Príncipe",
                            "Senegal",
                            "Serbia",
                            "Seychelles",
                            "Sierra Leona",
                            "Singapur",
                            "Siria",
                            "Somalia",
                            "Sri Lanka",
                            "Suazilandia",
                            "Sudán",
                            "Sudán del Sur",
                            "Suecia",
                            "Suiza",
                            "Surinam",
                            "Tailandia",
                            "Tanzania",
                            "Tayikistán",
                            "Timor Oriental",
                            "Togo",
                            "Tonga",
                            "Trinidad y Tobago",
                            "Túnez",
                            "Turkmenistán",
                            "Turquía",
                            "Tuvalu",
                            "Ucrania",
                            "Uganda",
                            "Uruguay",
                            "Uzbekistán",
                            "Vanuatu",
                            "Venezuela",
                            "Vietnam",
                            "Yemen",
                            "Yibuti",
                            "Zambia",
                            "Zimbabue"]
    
    func obtenPais() -> String {
        let position = Int ( arc4random() ) % self.paises.count
        return self.paises[position]
    }
}

class ColeccionDeHamburguesa {
    var hamburguesas: [String] = ["Hamburguesa de Tofu",
                                  "Hamburguesa de Pescado",
                                  "Hamburguesa de Pollo",
                                  "Hamburguesa de Soya",
                                  "Hamburguesa de Lentejas",
                                  "Hamburguesa de Atún",
                                  "Hamburguesa de Salmón",
                                  "Hamburguesa de Verduras",
                                  "Hamburguesa Vegetal",
                                  "Hamburguesa de Garbanzos",
                                  "Hamburguesa de Espinacas",
                                  "Hamburguesa de Pavo",
                                  "Hamburguesa Thermomix",
                                  "Hamburguesas de frijol",
                                  "Hamburguesitas de patata y cordero",
                                  "Hamburguesa con sabor a tomate",
                                  "hamburguesa samurái",
                                  "Hamburguesa mediterránea",
                                  "Hamburguesa Ibérica",
                                  "Hamburguesa tradicional"]
    
    func obtenHamburguesa() -> String {
        let position = Int ( arc4random() ) % self.hamburguesas.count
        return self.hamburguesas[position]
    }
}

class Colores {
    let colores: [UIColor] = [UIColor(red: 200.0/255.0, green: 16.0/255.0, blue: 46.0/255.0, alpha: 1.0),
                              UIColor(red: 100.0/255.0, green: 100.0/255.0, blue: 236.0/255.0, alpha: 1.0),
                              UIColor(red: 19.0/255.0, green: 41.0/255.0, blue: 75.0/255.0, alpha: 1.0)]
    
    func obtenerColor() -> UIColor {
        let position = Int ( arc4random() ) % self.colores.count
        return self.colores[position]
    }
}